class ErrorCode:
    SUCCESS = 0
    WRONG_USERNAME_OR_PASSWORD = 1
    USER_NOT_EXISTS = 2
    USER_ALREADY_EXISTS = 3
    UNAUTHORIZED = 4
    ROOM_NOT_EXISTS = 5
    ROOM_FULL = 6
    DECK_NAME_DUPLICATE = 7
    PLAYER_ALREADLY_PLAYING = 8
    PLAYER_NOT_PLAYING = 9
